name: NASA Project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# JObs to be done with every push  and pull request to main as specified above
# And all steps for each jobs
# checkout:
# node makes sure that the machine has node. make sure node is installed on machine running this build with ver 16. this step is named
# can run custom commands
jobs:
  build:
    env:
      CI: true # Will disbale watch mode.
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [14.x, 16.x] # will create 2 jobs running simaltaneously
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Use MongoDB from GitHub actions
        uses: supercharge/mongodb-github-action@v1.6.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm run test-server
